package Image;

public enum   Image {
    GRASS_TILE,
    JUNGLE_TILE,
    WHITE_SNAKE_GRASS,
    BLUE_SNAKE_GRASS,
    RED_SNAKE_GRASS,
    GOLD_SNAKE_GRASS,
    WHITE_SNAKE_JUNGLE,
    BLUE_SNAKE_JUNGLE,
    RED_SNAKE_JUNGLE,
    GOLD_SNAKE_JUNGLE,
    EGG_GRASS,
    EGG_JUNGLE,

}
